version: "3.7"

services:
  grafana:
    image: grafana/grafana:6.2.0
    container_name: drend-ms-analytic-grafana
    hostname: drend
    volumes:
      - "./persistency/drend-ms-analytic-grafana/data:/var/lib/grafana:rw"
      - "./persistency/drend-ms-analytic-grafana/config/grafana.ini:/etc/grafana/grafana.ini:ro"
    ports:
      - "127.0.0.1:3001:3000"
    restart: unless-stopped
    user: root
    environment:
      GF_SECURITY_ADMIN_PASSWORD: changeMeLater
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:v2.10.0
    container_name: drend-ms-analytic-prometheus
    hostname: drend
#    volumes:
#      - "./persistency/drend-ms-analytic-prometheus/config:/etc/prometheus:rw"
    ports:
      - "127.0.0.1:9090:9090"
    restart: unless-stopped
    user: root

