version: "3.7"

services:
  grafana:
    image: grafana/grafana:6.2.0
    container_name: drend_ms_analytic_grafana
    hostname: drend_ms_analytic_grafana
    volumes:
      - "./config/grafana/grafana.ini:/etc/grafana/grafana.ini:ro"
    ports:
      - "127.0.0.1:3001:3000"
    restart: unless-stopped
    user: root
    environment:
      GF_SECURITY_ADMIN_PASSWORD: changeMeLater
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:v2.10.0
    container_name: drend_ms_analytic_prometheus
    hostname: drend_ms_analytic_prometheus
    volumes:
      - "./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro"
    ports:
      - "127.0.0.1:9090:9090"
    restart: unless-stopped
    user: root

