version: "3.7"

services:
  swagger-ui:
    image: swaggerapi/swagger-ui:v3.22.2
    container_name: drend-ms-swagger-ui
    volumes:
      - "../api:/api:ro"
    ports:
      - "127.0.0.1:8100:8080"
    environment:
      SWAGGER_JSON: "/api/drend.yml"
    restart: unless-stopped