version: "3.7"

services:
  drend:
    hostname: drend
    build:
      context: ../drend
      target: dev
    volumes:
      - "../drend:/service:ro"
      - "./persistency/drend-ms-drend/static:/static:rw"
    image: drend-ms-drend
    container_name: drend-ms-drend
    ports:
      - "127.0.0.1:6060:6000"
    restart: unless-stopped
    environment:
      ADDRESS: ":6000"
      BACKLOG: 2048
      THREADS: 1
      MAX_REQUESTS: 0
      TIMEOUT: 10
      KEEP_ALIVE: 2
      LIMIT_REQUEST_LINE: 4094
      RELOAD: "--reload"
      NO_SENDFILE: "--no-sendfile"
      LOG_LEVEL: info
      NAME: drend
      LANG: en_US.UTF-8
